---
title: "課堂練習模版"
author: "Donna"
date: "2020-10-14"
output: output_format
params:
  id: "410672056"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
"\u0928\u092e\u0938\u094d\u0924\u0947 \u0926\u0941\u0928\u093f\u092f\u093e"
```

```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

```

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```


```{r}
#類別資料factor

majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)
#or
majors10_factor <- factor(majors10_char)

as.integer(majors10_factor)#顯示程式如何儲存這筆資料

typeof(majors10_factor)
class(majors10_factor)
```
```{r}
class("1")
class("1.5")
```
```{r}
as.numeric("1")
```
```{r}
a <- "1"
as.numeric(a) -> a #要再改一次a #指回去a取代的概念
a+4
```

```{r}
a <- factor(c("一","二","三"), levels())
levels(a) 

```

