---
title: "課堂練習模版"
author: "Donna"
date: "2020-10-28"
output: output_format
params:
  id: "410672056"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
# 有多少名字可選：
names(listExample)
```

```{r}
listExample$student
listExample$學期  # 特殊命名依然要用反頓點呼叫
```

```{r}
listExample[["student"]]
listExample$student

listExample[["學期"]]  # 小心不是反頓點喔。
listExample$學期
```

```{r}
vectorExample
vectorExample[c(1, 3)]
```

```{r}
vectorExample[c(1)]
vectorExample[1]   #取多個用一個中括號
vectorExample[[1]] #只取一個用兩個中括號
```


```{r}
vectorExampleWithNames[c("p1","p3")]
vectorExampleWithNames[c(1,"p3")] #錯誤，前後元素不同
#c告訴R這是automic vector
```

```{r}
vectorExample
vectorExample[c(T, T, F)]  # 要，要，不要(也可寫TRUE,FALSE)
```

```{r}
pickByNumber <- c(1,3)
pickByName <- c("P1","P3")
pickByLogical <- c(T, T, F)
```

```{r}
str(listExample,1)
listExample[c(1,2)]
listExample[c("student","學期")]
listExample[c(T,T)]
```
```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1, 4)]
select1
select2 <- select1[[1]]
select2

# 相當於
numVector[c(1, 4)][[1]]
```

```{r}
select1 <- numVector[c(T, T, F, T, F, F, T)]
select1
select2 <- select1[c(1, 4)]
select2

# 相當於
numVector[c(T, T, F, T, F, F, T)][c(1, 4)]
```
```{r}
majorsStudent <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
namesStudent <- c("小英", "小美", "大雄", "阿華", "阿尼")
genderStudent <- c("F", "F", "M", "F", "M")
```

```{r}
pickEcon <- c(T,T,F,F,T)
namesStudent[pickEcon]
genderStudent[pickEcon]
```
```{r}
pickEcon <- majorsStudent == "經濟學系"
namesEcon <- namesStudent[pickEcon]
genderEcon <-genderStudent[pickEcon]
```

```{r}
namesStudent[pickEcon][[3]]
```

```{r}
whichHasEcon <- which(pickEcon)
```

```{r}
pickEconNum <- c(1,2,5)
namesStudent[pickEconNum]
genderStudent[pickEconNum]
```
```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)
```
```{r}
weather[[1]]
str(weather[[1]])
```
```{r}
weather[[2]]
str(weather[[2]])
```
```{r}
weather[[1]][[1]]
weather[[1]][[2]]

weather[[1]][[2]][[2]][["highest_temp"]] #今天/台北市/最高溫
weather[[2]][[1]][[2]] #明天/台北市/最高溫
```
```{r}
listExample[["學期"]][["108-2"]][[1]][["teacher"]]
#等同於
listExample$學期[[]][["108-2"]][[1]]$teacher
```

```{r}
listExample$學期[[]][["108-2"]][[1]]$teacher <- "Jason"

#等同於Jason
listExample$學期[[]][["108-2"]][[1]]$teacher

#改名稱、成績
listExample$學期[[]][["108-2"]][[1]][c('name',"grade")]
listExample$學期[[]][["108-2"]][[1]]$name <- "統計學"
listExample$學期[[]][["108-2"]][[1]]$grade <- 80

#確定一下結構，保持結構可以一次大量修正
original <-listExample$學期[[]][["108-2"]][[1]][c('name',"grade")] 
class(original)
str(orginal)

```

```{r}
list(
  name="統計學"
  grade=78
)
```

