---
title: "課堂練習模版"
author: "Donna"
date: "2020-11-18"
output: output_format
params:
  id: "410672056"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
#以下八個為特徵變數 含四個資料點
#每個都是c()，皆為automic.vector
```

```{r}
library(purrr)
tr_example <- transpose(example)
str(tr_example)
```

```{r}
tr_example <- purrr::transpose(example)
str(tr_example)
```
```{r}
df_example <- as.data.frame(example) 
#過去list的element 變成在dataframe裡的variables
```

```{r}
# 使用list的工具
df_example$name[c(1,4)]

# 使用data frame的延伸工具`[.row, .column]`
df_example[c(1,4), "name"]
df_example[c(1,4), 1]
#repeat F 7times
df_example[c(1,4), c(T,rep(F,7))]

df_example[c(1),1:8]
df_example[1,]
df_example[1,]$hobby
#擷取第一人的所有資料[1,] 再取出hobby

df_example[1,][5] #feature轉90度 -> data.frame(是一種list)
df_example[1,][[5]] #character
```

```{r}

```

