---
title: "課堂練習模版"
author: "Donna"
date: "2020-10-07"
output: output_format
params:
  id: "410672056"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
#single threat:在error處即停止跑程式
```

```{r}
#值為文字需用雙引號或單引號：" " / ' '(有成對的概念)
char1<-"你好"
char2<-'你好' #單引號有些程式不接受
```

```{r}
#vNum2 <- c(2, num1)>2為一值,num1為一物件
vNum5 <- c(c(-1,5),c(2,3))=c(-1,5,2,3)

num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)

此時vNum2>c(2,2,5)
```


```{r}
#例題一：堆疊or覆蓋式紀錄
heightsOftheEntireClassroom <- c()

heightsOftheEntireClassroom2 <- c()
```

```{r}
heightOfAStudentComingInsideTheClassroom <- sample(165:200,1)
```

```{r}
# method 1: concatenate 
heightsOftheEntireClassroom <-
  c(
    heightsOftheEntireClassroom,
    heightOfAStudentComingInsideTheClassroom
  )#堆疊式記錄同學身高，正確
```

```{r}
# method 2: 
heightsOftheEntireClassroom2 <-
  heightOfAStudentComingInsideTheClassroom
#覆蓋式紀錄同學身高，錯誤
```


```{r}
#c(5,"Mary") #non-Atomic不同型態，不常這樣使用
c(5,7) #數字一組Numeric
c("John", "Mary") #文字一組Character
c(T,TRUE,F,FALSE)
c(T,T,F,F)
```

```{r}
num1<-5 # 非整數(5.0000...)
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)

object.size(num1Vector)
object.size(num2Vector)
```

```{r}
typeof(num1)
typeof(num2)
#程式儲存資料的型態
```

```{r}
char1Vector<-c("你好","How are you?")
#使用class()查詢上述物件類別。
typeof(char1Vector)
class(char1Vector)
```

```{r}
d1 <- '小明說：明天不用上課'
d2 <-"小明說：明天不用上課"
#元素相同
```

```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')
dialogue # 顯示原始值的內容（含輸入時的引號）
```

```{r}
cat(dialogue, sep="\n") # 顯示給人類看（含存出來）的值，sep="\n", 不同元素換行陳列。(\ means escpae：跳脫原始意思，避免一些難以閱讀的符號)
writeLines(dialogue, "conversation.txt") # cat顯示的正是存出來樣貌。
```

```{r}
context <- "老師說換行要寫\\n,\\是escape的意思" 
#\\負負得正的概念，不escape，因而會顯示\
cat(context)
```

